#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Linting and compiling TypeScript... Stand by for awesomeness! 🚀💻'

npm run lint ||
(
    echo '🚀 Uh-oh, Houston, we have a problem. 🛠️💻 Please fix the linting errors and TypeScript compilation issues before committing... 💪🔧'
    false;
)

# If everything passes... Now we can commit
echo 'Congratulations! Your code is looking great and ready for liftoff! 🚀'
